// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/workerpb/worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMs    int64                  `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_api_workerpb_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerpb_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_api_workerpb_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type WorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartAt       int64                  `protobuf:"varint,1,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         int64                  `protobuf:"varint,2,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	mi := &file_api_workerpb_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_workerpb_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_api_workerpb_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkResponse) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *WorkResponse) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

var File_api_workerpb_worker_proto protoreflect.FileDescriptor

const file_api_workerpb_worker_proto_rawDesc = "" +
	"\n" +
	"\x19api/workerpb/worker.proto\x12\bworkerpb\".\n" +
	"\vWorkRequest\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x03R\n" +
	"durationMs\"@\n" +
	"\fWorkResponse\x12\x19\n" +
	"\bstart_at\x18\x01 \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\x02 \x01(\x03R\x05endAt2F\n" +
	"\rWorkerService\x125\n" +
	"\x04Work\x12\x15.workerpb.WorkRequest\x1a\x16.workerpb.WorkResponseB\x0eZ\fapi/workerpbb\x06proto3"

var (
	file_api_workerpb_worker_proto_rawDescOnce sync.Once
	file_api_workerpb_worker_proto_rawDescData []byte
)

func file_api_workerpb_worker_proto_rawDescGZIP() []byte {
	file_api_workerpb_worker_proto_rawDescOnce.Do(func() {
		file_api_workerpb_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_workerpb_worker_proto_rawDesc), len(file_api_workerpb_worker_proto_rawDesc)))
	})
	return file_api_workerpb_worker_proto_rawDescData
}

var file_api_workerpb_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_workerpb_worker_proto_goTypes = []any{
	(*WorkRequest)(nil),  // 0: workerpb.WorkRequest
	(*WorkResponse)(nil), // 1: workerpb.WorkResponse
}
var file_api_workerpb_worker_proto_depIdxs = []int32{
	0, // 0: workerpb.WorkerService.Work:input_type -> workerpb.WorkRequest
	1, // 1: workerpb.WorkerService.Work:output_type -> workerpb.WorkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_workerpb_worker_proto_init() }
func file_api_workerpb_worker_proto_init() {
	if File_api_workerpb_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_workerpb_worker_proto_rawDesc), len(file_api_workerpb_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_workerpb_worker_proto_goTypes,
		DependencyIndexes: file_api_workerpb_worker_proto_depIdxs,
		MessageInfos:      file_api_workerpb_worker_proto_msgTypes,
	}.Build()
	File_api_workerpb_worker_proto = out.File
	file_api_workerpb_worker_proto_goTypes = nil
	file_api_workerpb_worker_proto_depIdxs = nil
}
